### PR TITLE
Breaking: Integrate with `window.history`, add setter method on `window.location`, improve tests and other project meta

### LINKED ISSUE #123: Conflicts with other tests, Possibly React Router v6
it works but changes the window globally which causes crashes at another test, so can be used to modify the window inside every single test spirality without reflection on other files?

### LINKED ISSUE #158: window.history.pushState not working as expected
window.history.pushState not working as expected when jest-location-mock is used.
clone [this](https://github.com/saravntbe/push-state-bug) repo to reproduce.
example (below test fails.)

```js
test('route should be changed', ()=>{
     window.history.pushState({}, 'Test page', '/123')
     expect(window.location.href).toEqual('http://localhost/123')
 })
 ```

### PR DESCRIPTION
**Pull request by evelynhathaway**
## Breaking
- Breaking: Add setter method on window.location
- Breaking: Add spies and proxy for window.history to track its updates to the original window.location (fixes #158, fixes #123)

## Improvements
- Docs: Add limitations, new features, alternative setup and configuration methods to readme (related to workarounds proposed in #123)

## Internal
- Chore: Simplify GitHub Actions npm cache

- Chore: Remove extraneous eslint disables
- Chore: Improve tests for existing logic

### CODE REVIEW

File: src/hooks/replace-history.ts
Comment (evelynhathaway) [inline src/hooks/replace-history.ts:1]: This file is where are majority of the net new value is.

We "replace" the history with a proxy to automatically update after any method is called. I could have made this an equally hacky replacement of each method with a spy that composes itself with an update function, but proxies are fun. (I wish Jest spies had events)

Jest spies on the methods on the proxy to provide access to call data to testers.

File: src/hooks/replace-location.ts [hunk 1]
```diff
@@ -16,15 +22,20 @@ export const replaceLocation = (): void => {
...
 		window,
 		"location",
 		{
-			value: locationMock,
+			get () {
+				return locationMock;
+			},
+			set (value: string) {
+				locationMock.href = value;
+			},
```
Comment (evelynhathaway) [inline src/hooks/replace-location.ts:36]: I didn't implement the setter on the first go of this library. Mostly because I don't use it instead of the many other options like `window.location.href =` and forgot! TypeScript's typings are also borked here, so maybe I am not alone lol.

This is technically a breaking change, so I am glad it can be lumped together with `window.history` support

**Comment by evelynhathaway** [comment]
[jsdom v23.1.0](https://github.com/jsdom/jsdom/releases/tag/23.1.0) has changed the `history` behavior. I should check to see what impact that may have to this PR

**Comment by Stanzilla** [comment]
> @Stanzilla Yes, I do plan to work on this MR. I haven't been super active with OSS recently because of life. I consider this MR and the new issue my top priority for when I'm able to next.
> 
> If you'd like to use this MR, there is an alpha version published to npm. I don't know if it fixes #168, but if it does, let me know! 😊
> 
> ```shell
> npm install -D jest-location-mock@3.0.0-alpha.1
> ```

Awesome, that is great to hear, thank you so much!

**Comment by sibelius** [comment]
it is breaking for me 

```
 TypeError: Cannot redefine property: location
        at Function.defineProperty (<anonymous>)

      at replaceLocation (../../node_modules/jest-location-mock/lib/hooks/replace-location.js:24:12)
      at Object.<anonymous> (../../node_modules/jest-location-mock/lib/setup-hooks.js:6:33)

```

I'm using latest jest version

**Comment by elchininet** [comment]
As a workaround for now, [one can just patch jsdom](https://gist.github.com/cpojer/e66f9a082021a82230f2595a6027f161) to avoid the `Cannot redefine property: location`.
